language: ruby
rvm:
  - 2.1.2
before_install: gem install bundler -v 1.11.2

addons:
    code_climate:
        repo_token: 0b8e41ecbc26637a7db4e6e9d4581c445441674f689016ab45fb5c51242b59bf

after_success:
  - bundle exec codeclimate-test-reporter